version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: nestjs-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: nestjs_db
      POSTGRES_USER: nestjs_user
      POSTGRES_PASSWORD: nestjs_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts/postgres:/docker-entrypoint-initdb.d
    networks:
      - nestjs-network

  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: nestjs-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: nestjs_admin
      MONGO_INITDB_ROOT_PASSWORD: nestjs_admin_password
      MONGO_INITDB_DATABASE: nestjs_mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init-scripts/mongodb:/docker-entrypoint-initdb.d
    networks:
      - nestjs-network

volumes:
  postgres_data:
    driver: local
  mongodb_data:
    driver: local

networks:
  nestjs-network:
    driver: bridge
